apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../../base

labels:
- pairs:
    env: development 
  includeSelectors: true
  includeTemplates: true

namePrefix: dev-
namespace: devns

replicas:
- name: dov-deploy 
  count: 1

images:
- name: chukmunnlee/cfdsa-dov-bear
  newName: chukmunnlee/dov-bear
  newTag: v5

configMapGenerator:
- name: dov-cm 
  namespace: devns
  behavior: create
  literals:
  - NAME=fred
  - EMAIL=fred@gmail.com

secretGenerator:
- name: dov-secret 
  namespace: devns
  behavior: create
  literals:
  - NAME=fred
  - EMAIL=fred@gmail.com

patches:
- target:
    group: apps/v1 
    kind: Deployment 
    name: dov-deploy
  path: patches.yaml
- path: delete-ingress.yaml

replacements:
- source:
    kind: Service 
    name: dov-svc
    namespace: dovns
    fieldPath: metadata.name
  targets:
  - select:
      kind: Deployment 
      name: dov-deploy
      namespace: dovns
    fieldPaths:
    - spec.template.spec.containers.[name=dov-container].env.[name=SERVICE_NAME].value
        
