---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy 
  #generateName: dov-deploy-
  namespace: myns
  labels: 
    app: dov 
    name: dov-deploy 
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: dov 
      name: dov-po
  template:
    # the pod template
    metadata:
      name: dov-po
      namespace: myns
      labels:
        app: dov 
        name: dov-po
    spec:
      containers:
      - name: dov-container 
        image: chukmunnlee/cfdsa-dov-bear:v1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: my-first-deployment
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000