---
apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata: 
  name: dov-hpa 
  namespace: dovns
  labels: 
    app: dovns 
    name: dov-hpa 
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: dov-deploy
  metrics:
  - type: Resource 
    resource: 
      name: memory
      target: 
        type: Utilization 
        averageUtilization: 60
  - type: Resource 
    resource: 
      name: cpu
      target: 
        type: Utilization 
        averageUtilization: 60